# Generated by Django 5.2.3 on 2025-06-20 08:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import trustwave.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(help_text='Enter your full name as it appears on your ID', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(help_text='Enter your phone number in format: +237XXXXXXXXX', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?237\\d{9}$', message='Phone number must be in Cameroon format: +237XXXXXXXXX')])),
                ('profession', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('merchant', 'Merchant'), ('farmer', 'Farmer'), ('civil_servant', 'Civil Servant'), ('healthcare_worker', 'Healthcare Worker'), ('other', 'Other')], default='other', max_length=20)),
                ('neighborhood', models.CharField(help_text='Enter your specific neighborhood in Bambili (e.g., Mile 4, Ntarinkon, etc.)', max_length=255)),
                ('id_card', models.ImageField(help_text='Upload a clear photo of your National ID card (JPG, PNG, or PDF)', upload_to=trustwave.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('supporting_doc', models.FileField(blank=True, help_text='Optional: Upload additional supporting document (JPG, PNG, or PDF)', null=True, upload_to=trustwave.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('validated', 'Validated'), ('refused', 'Refused'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', trustwave.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('success', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', 'timestamp'], name='trustwave_l_email_749ac4_idx'), models.Index(fields=['ip_address', 'timestamp'], name='trustwave_l_ip_addr_18f999_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Provide detailed information about the situation')),
                ('location', models.CharField(help_text='Specific location within Bambili (e.g., Mile 4 Junction, Ntarinkon Market)', max_length=255)),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('shops', 'Shops & Services'), ('charging_points', 'Charging Points'), ('security', 'Security'), ('transport', 'Transport'), ('health', 'Health Services'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload a photo as proof (JPG or PNG)', null=True, upload_to=trustwave.models.report_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('video', models.FileField(blank=True, help_text='Upload a video as proof (MP4, MOV, or AVI)', null=True, upload_to=trustwave.models.report_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])])),
                ('document', models.FileField(blank=True, help_text='Upload a document as proof (PDF, DOC, or DOCX)', null=True, upload_to=trustwave.models.report_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='trustwave.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('vote_cast', 'Vote Cast'), ('question_asked', 'Question Asked'), ('profile_updated', 'Profile Updated')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_asked', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='trustwave.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['category', 'created_at'], name='trustwave_r_categor_e642e7_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['location', 'created_at'], name='trustwave_r_locatio_d5400c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_verified', 'created_at'], name='trustwave_r_is_veri_beddfd_idx'),
        ),
        migrations.AddIndex(
            model_name='reportvote',
            index=models.Index(fields=['report', 'created_at'], name='trustwave_r_report__2dadb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportvote',
            unique_together={('user', 'report')},
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'timestamp'], name='trustwave_u_user_id_7607a7_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type', 'timestamp'], name='trustwave_u_activit_8ed3de_idx'),
        ),
    ]
